### ISSUE TITLE
Subscriptions missing.

### ISSUE THREAD

**Issue by gbdrbob** [UncleGoogle/galaxy-integration-humblebundle#136]
**Describe the bug**
Intalled latest 0.9.0 release - signed in to Humble bundle - trove games not listed, nor is humble monthly

**Expected behavior**
Humble monthly and Trove games should be synced and listed

**Plugin installed**
Manually from your repository releases

**Provide logs**
Log archive attached. I believe the following line in the logs may be key:

`2020-08-08 15:54:22,602 - galaxy.http - WARNING - Got status 400 while performing GET request for https://www.humblebundle.com/api/v1/trove/chunk?index=0&ajax=true`

[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/5046502/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip)

![image](https://user-images.githubusercontent.com/17690288/89717926-f40b2a80-d9b2-11ea-8378-f8aa6fffa186.png)

**Comment by UncleGoogle** [comment]
Hey, thanks for report. 

trove issue you found should is fixed in 0.9.0 (this log msg is from 0.8.1) but there is another breaking change humble model from subscriptions. I'll fixed soon when have a free time slot and maybe I should think how to make subscriptions interface more robust for future humble changes...
