### ISSUE TITLE
Import message doesn't close

### ISSUE THREAD

**Issue by hightower5** [UncleGoogle/galaxy-integration-humblebundle#177]
The info window for importing Humble Bundle games does not close automatically.

![Screenshot 2022-05-14 120300](https://user-images.githubusercontent.com/18751660/168421254-68974264-450f-41dc-81a4-995be953e927.jpg)

**Comment by UncleGoogle** [comment]
Hello, I don't have this problem. Please send some logs to me for - the instruction is written in template of a new issue.

**Comment by hightower5** [comment]
[plugin-humble-log.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/8698824/plugin-humble-log.zip)

**Comment by SkebbZ** [comment]
same thing here
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/8699103/logs.zip)

**Comment by SkebbZ** [comment]
I now see that I was stuck at 0.9.5, assuming this is related to #176.
Manually updating to 0.10.0 seems to have created a different problem, however.
Now it connects, then states "connection lost" about three seconds later
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/8700052/logs.zip)
.

**Comment by hightower5** [comment]
@SkebbZ you describe exact my problem.

**Comment by UncleGoogle** [comment]
Ok, so the cookie was invalidated so initialization shoulnd't pass,  you should be able to reauthenticate.
Try to click disconnect before "connection lost", then relogin should be fine. I'll try to fix when have time.

**Comment by UncleGoogle** [comment]
If you would like to test - close Galaxy, replace one file content in the installed plugin directory - `webservice.py`  - with this: https://github.com/UncleGoogle/galaxy-integration-humblebundle/blob/auth_lost_from_authenticate/src/webservice.py
restart Galaxy

**Comment by UncleGoogle** [comment]
@SkebbZ 

> To be clear, the import thing and CPU usage went away with v0.10.0

thanks for clarification. I don't know why it happen on 0.9.5 thought

One more issue in your logs:

```
2022-04-08 22:16:16,240 - settings - INFO - Loaded config: {'library': {'sources': ['trove', 'keys', 'drm-free'], 'show_revealed_keys': False}, 'installed': {'search_dirs': ['D:\\Spill']}}
2022-04-08 22:16:16,241 - settings - ERROR - Parsing config error: ValueError("'trove' is not a valid SOURCE")
```

I'll add systematic fix, but meantime you can clear trove  key from file under this path: https://github.com/UncleGoogle/galaxy-integration-humblebundle/blob/7594a6ce1000cc8173714e80e3e12f36378b8f84/src/settings.py#L100

**Comment by hightower5** [comment]
> If you would like to test version that properly handle loosing authentication - close Galaxy, replace one file content in the installed plugin directory - `webservice.py` - with this: https://github.com/UncleGoogle/galaxy-integration-humblebundle/blob/auth_lost_from_authenticate/src/webservice.py restart Galaxy

I have installed manually version 10.0 and replace 'webservice.py' with the new one. For me, the plugin 10.0 works now.

**Comment by SkebbZ** [comment]
I purged the settings file and set it to "drm-free" only. 

It connects properly now, but after connecting the entire GOG client slows to a crawl and uses 100% CPU on the "GalaxyClient 
Helper Application". If I terminate that process the GOG client sort of reloads and imports everything normally after a few seconds. 

Seems to work OK, until I restart the client. Then it starts to use around 10-12% CPU on the Python process related to the Humble plugin. I know this because when I terminate it, it says "Humble plugin crashed".

[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/8709281/logs.zip)

_Side note:
The entire client was always a bit unstable. Perhaps I just have too many games. If I import my steam account, the entire client crashes or becomes unusable due to having over 4k games there...

At least on Humble I only had 397 drm-free games when I unticked everything else._

**Comment by UncleGoogle** [comment]
> It connects properly now, but after connecting the entire GOG client slows to a crawl and uses 100% CPU on the "GalaxyClient
Helper Application". If I terminate that process the GOG client sort of reloads and imports everything normally after a few seconds.

no idea...

> Seems to work OK, until I restart the client. Then it starts to use around 10-12% CPU on the Python process related to the Humble plugin. I know this because when I terminate it, it says "Humble plugin crashed".

that's disturbing. Could you set a new issue for that? 
is it 12% of the whole available CPU compute power or 12% of the currently used CPU power? Because in the latter case it is quite normal that during the idle, small background processes takes majority of the currently used power.

In the logs I see that all the initial import takes around 1minute. Then - there is nothing interesting - only "pong"'s for galaxy "pings" if the plugin is still alive

**Comment by SkebbZ** [comment]
> that's disturbing. Could you set a new issue for that? is it 12% of the whole available CPU compute power or 12% of the currently used CPU power? Because in the latter case it is quite normal that during the idle, small background processes takes majority of the currently used power.
> 

Created a new issue and put a screenshot there.
