### ISSUE TITLE
Empty library

### ISSUE THREAD

**Issue by fonsosm** [UncleGoogle/galaxy-integration-humblebundle#3]
I have logged in HB, the bookmark appears inside Galaxy, but the game library is empty.

![wefwef](https://user-images.githubusercontent.com/36267339/61584323-0915e100-ab46-11e9-85f6-412cfd354ffe.png)

**Comment by UncleGoogle** [comment]
Can you send me your log file? It's there:
```%programdata%\GOG.com\Galaxy\logs\humble_xxxxx.log```

**Comment by fonsosm** [comment]
Here it is:

[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3414013/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)

Thanks!

**Comment by dakotathrice** [comment]
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3414116/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)

Here's mine as well, I'm seeing exactly the same thing, the client has created the bookmark/filter but hasn't actually pulled any game data.

**Comment by UncleGoogle** [comment]
Hi! @fonsosm, @dakotathrice try this:
[humblebundle_0.1 - authfix.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3414458/humblebundle_0.1.-.authfix.zip)
and let me know if this helps. If not, please send logs again - I've put there more debug info.

**Comment by fonsosm** [comment]
Perfect! I can see now my HB library. 

Thanks!

**Comment by dakotathrice** [comment]
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3414767/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)

Still nothing showing in the client for me though looking at the newer log it is at least getting something from Humble.

**Comment by UncleGoogle** [comment]
Your log doesn't start from the begging - only from the moment your games are imported. That is good signal, so there were no errors on plugin side until sending owned_games.
But, we detected 578 DRM-free PC-like games... That means looong fetching for the results on our side and even longer importing games time from Galaxy backend.

Have you tried to wait 10 minutes after connection?

**Comment by dakotathrice** [comment]
Just checked back on it and there's still nothing showing in the client.

**Comment by UncleGoogle** [comment]
@dakotathrice I've optimize fetching orders. Try with this and sends me __all__ `plugin_humble*_` logs please

[humblebundle_0.1.1.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3414833/humblebundle_0.1.1.zip)

**Comment by dakotathrice** [comment]
That's worked.  After a quick comparison I'm missing about 80 games but I also have a similar number of unknown game entries in Galaxy so I'm guessing there's going to be  a lot of crossover between them. There's just no way for me to match them up as there's no identifying data at all. 

Thanks for the help getting it working though.

**Comment by UncleGoogle** [comment]
No problem, bugs should be fixed :)
Do you wish to help me in one more thing? As you have so many games, it would be nice to grab your games structs for testing. Plugin that additionally log game orders:

[humblebundle_0.1.2 - log all games.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3416382/humblebundle_0.1.2.-.log.all.games.zip)

No sensitive data. Procedure like in previous post.

**Comment by UncleGoogle** [comment]
Release 0.1.2 with both fixes

**Comment by dakotathrice** [comment]
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3418294/logs.zip)
All the unknown games are still listed as such however a few of them have now pulled images and looking at the others it seems they all have the product name on the edit pop-up so I will be able to match them up. If there's any other info I can provide that might help just let me know.

**Comment by PookaMustard** [comment]
@UncleGoogle, how did you fix this issue? I'm suffering from a similar issue with the plugins I've been writing, and I don't know why. The logs do show that Galaxy should have received both owned games and local games...

**Comment by UncleGoogle** [comment]
Hi,
Empty library is too general symptom to say something useful. Can you link to your code? But if your plugin sends data, as you said, in form of `Sending data: {"jsonrpc": "2.0", "id": "6", "result": {"owned_games": ` it looks like it is probably not your plugin problem and I would create an issue for them or ask on galaxy api github page.

As your problem with hb is concerned, its different issue. Looks like Galaxy has canceled fetching for owned games due to 1minute timeout has passed without the result. It is quite a long time though. dekotathrice in this topic has 2,5 more games to fetch than you, and it took 13seconds. Please try again and if it doesn't help, create another issue. If your internet connection was not so horrible and it was not humble bundle server lag that time, I will try to fix this somehow.

**Comment by PookaMustard** [comment]
I didn't have the time out problem this time and the library imported. A question though. Time out in this case means not even a single response was sent back, right? Because if it means there are responses but they're taking their merry time to arrive, then I've got a problem. My internet isn't known for being good.

Also, I should send my logs for my game data later.

About my plugin, here it is. Extract it to the lookup directory, edit the settings.json to point to a large bunch of NES ROMs (or even zip files of any kind, those can do for the importing), and see if the library imports for you. The log file is also included. For me, it only imports if I point it at a small library of like ten items. Somewhere, even at around 50 items, no importing happens. In the log file, I point it to my NES ROMset of 1,000+ ROMs.

[nes_2abe73e6-75f6-4c36-9080-5dddb4de1f62.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3448207/nes_2abe73e6-75f6-4c36-9080-5dddb4de1f62.zip)

**Comment by UncleGoogle** [comment]
>  Time out in this case means not even a single response was sent back, right? 
No, I'm using asyncio.gather to handle ~200 of your requests at once. So currently don't know in what point it was cancelled. What we can do is to
- chunk data requests for example 20 per one gather
- if it lasts too long, return what we have so far; then run task to add the rest via `add_game` notifications method.
You can fork and experiment. I it will work for you, PR are welcomed.

Your logs looks ok. My guess is that Galaxy do not support all platforms for now, or their gamesdb has some protection anti-spam filters. But it is a guess, you can always ask them.
