### ISSUE TITLE
Missing Games in library

### ISSUE THREAD

**Issue by Riku55** [UncleGoogle/galaxy-integration-humblebundle#37]
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3753049/logs.zip)
[config.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3753058/config.zip)

I compared the list of the current Trove games to my galaxy list and there are 6 games missing. I just bought Humble Monthly for the first time a few days ago, so it is active right now.
Those games are:

Roman Sands
Shady Knight
Kind Words
20 Minute Metropolis
Star Wars: X-Wing vs TIE Fighter - Balance of Power Campaigns
AI War Collection 2014

Using version 0.5-alpha3, removed 'keys' from sources in config, added one (existing) path in installed, that is currently empty though. No Humble Bundle games installed yet.
Windows 10, 64-bit.

**Comment by Riku55** [comment]
I just checked my Humble Library and found 3 more games that are not added to Galaxy:

AI War: Fleet Command+3 DLCs
Mountain 2.0
TIMEframe

**Comment by UncleGoogle** [comment]
Thanks for report!
From logs I see that all those games except TIMEframe are send from the plugin properly. I think the problem was already risen as a part of this: #28
I repaste "solution" for others:

> **Game not shown at all** - sometimes games are not shown at all even if are send via integration (see log file). This happens with all products that can be classified as "not-games". For example game's audio (if not filtered out by #18) or DLCs. They are hide in Galaxy backend after some time, like someone do it manually every time the new game title/id is coming.
> 
Solution: send bug report to Galaxy with game titles and ids. 

This is galaxy gamesdb problem and they can fix it within 2-3 weeks after reporting (based on data from galaxy dev discord channel)
-------

TIMEframe - in logs I cannot found string like this. Could you please send me json reponse from humblebundle about this game?

- open devtools
- click on Network tab
- nagivate to https://www.humblebundle.com/home/library
- click on after one on requests of name like on image below
- search for game name in Response subtab

![39055cc457338616633fa89f1ed95a38](https://user-images.githubusercontent.com/12197825/62280139-a2e56400-b44b-11e9-907b-c085dc2c0aa4.png)

repaste it here please. Remove sensitive data (redeemed_key_val values).

**Comment by Riku55** [comment]
I just rechecked TIMEframe in my Humble Library and it actually is Steam only with the key redeemed already, so that's not a problem on your side. I don't really get why it was in the list when filtering for Windows and Direct Download (especially as it was the only faulty one), but it's not there anymore anyway, so I guess we can mark this one as solved.
I will report the rest of the games in mantis2, thank you :)

**Comment by Diskutant** [comment]
@Riku55 did you get a reply from GoG? I have the same problem, I only became aware of it because the new Operator game doesn't show up in GoG.

**Comment by Riku55** [comment]
> @Riku55 did you get a reply from GoG? I have the same problem, I only became aware of it because the new Operator game doesn't show up in GoG.

Nope, nothing yet, you can look at the report here: https://mantis2.gog.com/view.php?id=17390
