### ISSUE TITLE
Include unactivated keys

### ISSUE THREAD

**Issue by RandomHam** [UncleGoogle/galaxy-integration-humblebundle#6]
Hey,

I was wondering if it would be possible to include keys as well, I it would also be nice if the integration would only scrap keys that are not redeemed yet.

Maybe I am the only one, but I prefer not to activate a game key from humble bundle if I don't intend to play it immediately. Therefore this would be help me to easier track which games I own already.

Nonetheless, thanks for the work you've done already!

**Comment by UncleGoogle** [comment]
Hi,
thanks for raising this.

>  I it would also be nice if the integration would only scrap keys that are not redeemed yet.

This is exactly the same I was thinking about. All activated stuff should be handled by the other plugins like Steam, Origin.

Currently I would easily fetch all keys, probably filter out activated one's and import to library. Then, on clicking "Install", open external browser for this game on humblebundle.com.

But I thing it would be much better if I could open internal Galaxy browser, like the one for logging. This will ensure that the proper account is logged in. I don't know who is logged in external browser, so I would be unfortunate to redeem a game for someone else ;)

Currently it is not possible, I'll create an issue on Galaxy API site.

**Comment by Itay080** [comment]
Hi!
Thanks for your work :)
If you do include this feature, please give us a way to differentiate between activated and unactivated games.
I have some games which I save for gifting/trading and would not want to accidentally activate them 😟

**Comment by UncleGoogle** [comment]
Hi, an update this feature plans.

- due to security reasons I will open external browser to show humble order page
- only games with not *revealed* keys will be shown
- games that are revealed (secret code is shown) but not *reedemed* (activated) on external account (Steam, Uplay, ...) won't be shown - the plugin has no idea on which account the code was redeem, so the simple check if a key was reedemed is platform dependent and probably impossible.
- the feature will be shipped after support for installed games, as it is more important, but hopefully in this month :)

**Comment by JD557** [comment]
It would be pretty cool to have this behavior configured somewhere (even if it one had to update a `.py` file manually for now).

I would like to see 3 levels:
* Show all games
* Show not revealed + trove
* Show trove only

Personally, I would rather only have this integration showing humble trove games, since all my unrevealed humble keys are games that I already own, but might want to gift on a later date (so I don't want to reveal them by accidently pressing "install").

**Comment by UncleGoogle** [comment]
@JD557 

> - Show all games

Do you mean revealed and not revealed as well as DRM-free games?

| Game type  | Action under Install button |
| ------------- | ------------- |
| DRM-free game | download relevant file  |
| Trove (DRM-free) | download relevant file; if failed due to subscription expiration -> open humblebundle.com/monthly  |
| DRM game with not revealed key | open humblebundle.com/home/keys in webbrowser |
| DRM game with revealed key | the same as for not revealed ?? |

**Comment by JD557** [comment]
I haven't really thought about that, TBH, but doing "the same as for not revealed" sounds good.

It might be helpful if you have revealed the key but forgot to activate the game (since gog galaxy shows repeated games, already activated games are easy to find).

**Comment by nicknicola** [comment]
I would prefer that it would show only DRM-free game and Trove (with the possibility of disabling it when im not subscribed). 
I really dont want to see all the unredeemed keys I have and clutter the Gog galaxy with games that are in the end steam keys. 
If its an option I have not problems with it though.

**Comment by UncleGoogle** [comment]
Prerelease for you guys ;)

[humblebundle_0.4c.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3546924/humblebundle_0.4c.zip)

Tell me how do you like it, please.

Play with a config.toml file in which everything should be explained. (Deduplication doesn't work yet).

In short, there is an option to show games from:
- drm-free
- trove
- keys

and revealed/not revealed boolean for the keys.

**Comment by RandomHam** [comment]
Hey, thanks for all the effort! Currently it does only integrate keys from the "Key" section from the account library (see screenshot). I don't know if that's intended to test the functionality, but if that means that potentially all categories can integrated, that would be amazing! (I guess I never made clear what I want to be integrated as well)

![image](https://user-images.githubusercontent.com/9338392/63791926-cab9d180-c8fc-11e9-8ab0-53ba3a9a0508.png)

As to the customization-solution, I hope everyone will be happy with it. At least I am, but I guess the functionality is very depended on use-case. Personally, I just want to know what games I own already, without having to immediately activate the keys and bind them to certain account.

Awesome job!

**Comment by UncleGoogle** [comment]
Merged. Note that this will be released with 0.4 release. Config settings may change
