### ISSUE TITLE
No results in games list

### ISSUE THREAD

**Issue by dstumme** [UncleGoogle/galaxy-integration-humblebundle#7]
**Describe the bug**
No games appear in the games list.  Secondary symptom - Humble Bundle does not appear on the platform list if I check the Filters.

**Expected behavior**
I have bought games from Humble that have non-DRM versions available for download. I expected those games to be visible.

**Screenshots**

**Attach logs**
(removed)

**Comment by UncleGoogle** [comment]
Should be fixed in [0.2.3](https://github.com/UncleGoogle/galaxy-integration-humblebundle/releases/tag/v0.2.3)

Looks like you have game on platform "asmjs" - superhexagon. Is it something running within web browser? Its download struct was unrecognized, as I wrongly assumened every download_struct should have "url" field. Now, it is ignored.

**Comment by UncleGoogle** [comment]
@dstumme please use this - it will report this game details, so I can do more in this future with it.
[humblebundle_0.2.3.1.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3439260/humblebundle_0.2.3.1.zip)

**Comment by dstumme** [comment]
Got the library loading now.  Anything else you need, or should I close the issue?

**Comment by UncleGoogle** [comment]
No, thanks for help!
