### ISSUE TITLE
Humble Choice selections

### ISSUE THREAD

**Issue by JMnITup** [UncleGoogle/galaxy-integration-humblebundle#73]
**Is your feature request related to a problem? Please describe.**
Humble Monthly is now Humble Choice, and provides options rather than just giving keys... it's a little annoying IMHO, but I guess is good if you wanted more control over what you actually get.  As it is now, though, the available games don't show in the list until they are selected (which I believe requires redeeming the key)

**Describe the solution you'd like**
Ideally, these options would show up in titles.  It's a little strange, because there might be 10 in the list but you can only choose 8, so technically you might not own 2 of the options, and if you've already chosen your limit, the unchosen ones aren't available, so it adds a bit of a wrench into the process... but, knowing what I COULD choose and having them in my games library is valuable to me so that I don't buy it elsewhere, etc.

**Describe alternatives you've considered**
Showing all in the list as 'potential' games is one option... not showing games if you have the max is another.  

**Additional context**
Not sure what their API exposes, and there's a Classic and Choice sub, where choice only gets 9 but classic gets 10 options, so there are some variables that could make things more complicated

**Comment by UncleGoogle** [comment]
Thanks for info about Humble Choice. 

I have to though about this. I'm not sure if letting not owned games show in Galaxy is in general the good idea. I would rather wait for better license type support before implementing it; see https://github.com/gogcom/galaxy-integrations-python-api/issues/55

**Comment by JMnITup** [comment]
Yeah, it's a weird one.. however, arguably, any games on a subscription have a similar problem of conditional availability.  The Humble Bundle Trove games are all in your library, until your subscription stops, then they aren't available... similarly, the Humble Choice options are all technically 'available' until you've made all of your selections, then the remaining ones aren't available anymore.

Same goes for other subs not covered by this plugin (xbox game pass, Origins sub, etc), and this type of approach seems likely to become a norm at some point, so probably worth both thinking about and seeing how other integrations are approaching it (and if Galaxy itself has any plans for how to support that paradigm)

**Comment by UncleGoogle** [comment]
Perfect argumentation ;)

However it would be much harder to design than Troves both in coding and in UX. What we need is:
- [ ] get list of current month games to choice eg: https://www.humblebundle.com/subscription/december-2019 (I do not see any classic request, how they are fetched via page javascript? We may scrap a page though)
- [ ] if scrapping: research if we can get gameid properly for real store element, otherwise mocking 10 new games every month may result in temporarily "unknown games" from Galaxy backend
- [ ] check user subscription type. At least should be defined in config but it would be lovely to have simple way to automatically distinguish few cases:
- no subscription
- basic (pick up to 3/10)
- premium (pick up to 9/10)
- lite (for validation if trove only can be used)
- classic subscription: https://support.humblebundle.com/hc/en-us/articles/360036284854-Humble-Choice-FAQ#classic - just check if we need it - probably not
- (optional: has subscription in the past but currently not activated (to keep track of historical titles?))
- [ ] option in config to add "choice" titles to library (another entry next to "keys" and "trove"
OR
- [ ] Choice mode on/off - mode where ONLY Choice titles are shown 
- [ ] research activations. Maybe we can then use "Install" button and pick games directly from Galaxy.
- [ ] implement logic where you can choose 9 or 3 games

A lot of work. If you have any ideas please share in this topic.

**Comment by UncleGoogle** [comment]
New [Galaxy API version](https://galaxy-integrations-python-api.readthedocs.io/en/latest/galaxy.api.html#galaxy.api.plugin.Plugin.get_subscription_games) has introduced interface for subscription games. I feel it perfectly fits with Humble Choice needs. Implementing this will be the next goal of the plugin.

**Comment by phillipd-porch** [comment]
Missed this one when commenting on the other issue. Excited to see this coming next. :)

**Comment by UncleGoogle** [comment]
Yes, me to ;)

After last Galaxy update, my idea for Choice support is:
- return every month as separate "subscription" under name like "Humble Choice April 20"
- later on provide simple GUI for Install button with basic information like how many games can you pick for given month and with activation option - if possible - or "open in browser" link.

And now to be decided:
- should we show already choosen subscription games if you already hide those leaving only those you don't picked already?*
- should we hide subscription games from given month only if no "game pick" has left?
- or maybe do it configurable like current "show_revealed_keys" case?

*Galaxy does not provide notification to dynamically add/remove _subscription games_, like it is done for _owned games_. Changes for subscription_games could be displayed after "Sync integrations" or Galaxy restart.

**Comment by phillipd-porch** [comment]
I think having everything under a separate subscription is perfect since it lets you sort. Though I have a slight preference for names like "Humble Choice 2020-04" for sorting reasons. I'm not sure how their UI handles it since I haven't seen any yet.

Personally, I think it does make sense to show already chosen games though having _that_ configurable could be handy. It's still useful information for knowing where they came from.

Though I'm not exactly following what happens if you choose it and redeem the Steam key? It will very much show up in Steam that way, right. Would it show up twice? You don't technically own two copies on two platforms so that might be a bit confusing.

But it does 100% make sense to me to hide them completely when there are no "game picks" left. This is showing the games you own and once you don't have any picks left you _can't_ own those, even if they were part of the subscription.

**Comment by UncleGoogle** [comment]
> "Humble Choice 2020-04" for sorting reasons.

Good idea, I'll check how it behaves in practice.
What about including number of left choices in this "subscription name"?

>Personally, I think it does make sense to show already chosen games though having that configurable could be handy. 

Ok, so I'll add configurable as v2 if there would be more interest for it.

> It's still useful information for knowing where they came from.

Yes. I have to check how Galaxy behaves when there is game in subscriptions AND in owned.

>Though I'm not exactly following what happens if you choose it and redeem the Steam key? It will very much show up in Steam that way, right. Would it show up twice? You don't technically own two copies on two platforms so that might be a bit confusing.

Same situation already exists in Keys support. Galaxy stack those games under one cover and you can select which one to see (aka deduplication). But again - will check subscription vs owned behavior when game is on different platform.

> But it does 100% make sense to me to hide them (the games you can't have anymore, not the whole subscription with the games you already picked) completely when there are no "game picks" left.

Agree.

**Comment by UncleGoogle** [comment]
Two questions:

1. Early Unlock

>The auto-payment date for Humble Choice is the last Friday of every month. (...) Customers who are already subscribed to Humble Choice can pay early to receive their games as soon as that month is available. Simply go to the Humble Subscriber Hub and click the "Unlock My Choices" button for the current month. 

https://support.humblebundle.com/hc/en-us/articles/217300487-Humble-Choice-Early-Unlock-Games

This endpoint `https://www.humblebundle.com/api/v1/subscriptions/humble_monthly/subscription_products_with_gamekeys/` shows your subscription games content and made choices but only for "unlocked" month. So user have to click "Unlock you choices*"

**The question for anyone that has not used Early Unlock for any of previous months (not May) AND has not activated any of games from that month**:
- does the endpoint returns any data for that month?

2. Humble Monthly

As far as I know, games from old subscription plan known as *Humble Montly* were activated automatically and thus were shown as owned_games in normal Galaxy library automatically. 

Do you think is there a sens to display them also in subscription plan?
If yes, what about aggregate them under one subscription named "Humble Montly" instead of dividing for separate months? Dividing for separate months make sens for Choice to keep track of made choices, but I'm not sure about Humble Montly.

**Comment by UncleGoogle** [comment]
Hey! A few nights left and I think prove of concept is shareable now!
Launching / Installing not supported yet, just listing the games.

Attached for testing for you guys. Follow install instructions from readme
[humblebundle.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/4625015/humblebundle.zip)

Let me know what do you think

**Comment by phillipd-porch** [comment]
For that endpoint, I see April 2020 and March 2020 but I'm not sure how to tell if I did the early unlock. I'm not seeing it mentioned anywhere and I don't remember. But I only see April and March and I see February and January on the website.

And I like the idea of Humble Monthly coming in as one aggregate plan. You're exactly right that you don't need to track choices but it's still nice to see what games came from there. But every month could get overwhelming quickly.

It's looking great though. Under subscriptions I'm seeing all the Humble Choice bundles including May. I think I was even seeing it before I unlocked it actually?

Though it looks a bit weird with the Humble Bundle link on the left which filters to owned games and not just subscriptions? I see subscriptions groupings there too but I only see 1-2 games under them? It looks like they might be the extras that are included even if I haven't picked them but it's still a bit weird because it doesn't seem to be all of them. Like, I see 3 games in the extras but only 2 in GOG. And it's not showing the ones I claimed/own from those months.

**Comment by UncleGoogle** [comment]
Thanks for testing!

> Though it looks a bit weird with the Humble Bundle link on the left which filters to owned games and not just subscriptions? 

That is on GOG how they display it. Owned games and subscription games are provided by separate plugin methods.

> I see subscriptions groupings there too but I only see 1-2 games under them? It looks like they might be the extras that are included even if I haven't picked them but it's still a bit weird because it doesn't seem to be all of them. Like, I see 3 games in the extras but only 2 in GOG. And it's not showing the ones I claimed/own from those months.

Looks like a bug. All extras and all possible choices should be displayed. 
Can you paste your logs? I've explained how to find them in bug report template (click report issue and you will see.) Zip them after 
a few minutes from restarting Galaxy - new subscriptions import may last some time

**Comment by phillipd-porch** [comment]
I attached logs here. I realized I could have just pasted them here but I was just following the directions on the report issue section and didn't think about it until after. I'm a bit sleep deprived still with a 16 week old. 🤣

Let me know if that's not showing what you need to see. Thank you!

https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/109

**Comment by UncleGoogle** [comment]
No problem, let continue discussion about this bug in the separate thread.

Hah, understand. I'm expecting my daughter to be born this week... sooo not much time left for this feature ;)

**Comment by UncleGoogle** [comment]
Hey, check out this: https://github.com/UncleGoogle/galaxy-integration-humblebundle/releases/tag/v0.8.0-alpha
