### ISSUE TITLE
Disable Install button for Humble library games that cannot be installed (os compatibility for keys)

### ISSUE THREAD

**Issue by branflaker** [UncleGoogle/galaxy-integration-humblebundle#82]
**Describe the bug**
Own a console-only game in your Humble Bundle library.  It cannot be downloaded or installed from Humble Bundle.  It only has a key.  Sync your Humble Bundle library with GOG Galaxy 2.0 using the plugin.  The Install button is enabled for all synced games, including those that cannot be downloaded, like the console-only games.

**Expected behavior**
The Install button should be disabled, as when dealing with games that cannot be installed.

**Plugin installed**
manually from your repository releases

**Provide logs**
This log shows the output of trying to install a game that cannot be installed.  In this case, it's Okami HD for PS3.
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/4042153/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip)

**Comment by UncleGoogle** [comment]
Thanks for report!

os_compatibility is already implemented but from your logs I see that the real problem is here #62 

Actual proper behavior should be displaying minimal GUI with information about the key.

Can you restart Galaxy and try again? (answer in #62 please, I'm closing this)

**Comment by branflaker** [comment]
Even after restarting, I still have the Install button enabled.

The example I used, Okami HD, is filtered as a Windows compatible game.

**Comment by UncleGoogle** [comment]
I read your log file once again and see that you're using v5.0 and there are some errors that should be fixed in newer version. FriendsOfGalaxy version (that is available via Galaxy install) is autoupdating.

> Expected behavior
> The Install button should be disabled, as when dealing with games that cannot be installed.

I'm not sure about this in general. because this plugin treats all `keys` as special type - so in current implementation clicking "Install" should display the key like that:
![ac1846a3176ca949d06c2292b2d36b73](https://user-images.githubusercontent.com/12197825/72190166-2776de00-33ff-11ea-8d9d-73f32702328e.png)

So there are two solutions:
1. keys should be always OS agnostic (in the future it may open steam probably?)
2. keys should be treated as the rest of games and shows "Install" available when a game is available on current system

Currently plugin sends always "None" as an answer to `get_os_compatibility` for `keys`.

(API)[https://galaxy-integrations-python-api.readthedocs.io/en/latest/galaxy.api.html#module-galaxy.api.plugin]:
> OSCompatibility flags indicating compatible OSs, or None if compatibility is not know
I didn't check what will happen for returning OSCompatibility(0)

So probably Galaxy fallbacks to their gamesdb that fetches from idgb as far as I know - and apparently your game is available there (in general) for Windows: https://www.igdb.com/games/okami-hd

I would rather go to solution 1, than 2, as current functionality of "keys" has other meaning for "Install" button that is OS agnostic.

What do you think?

**Comment by UncleGoogle** [comment]
So, @branflaker how do you think?
1, 2 or do nothing (leaving decision to Galaxy/igdb)? 
If `OsCompatibility` serves only to disable/enable Install button I would do 1 (enable for all keys) just for consistency & to be able to show small GUI with additional information (the proper name, key for which provider and if it is revealed or not).
But as it also serves for filtering games in Galaxy UI, I'm not so sure.

**Comment by branflaker** [comment]
This is a generally special case for Humble Bundle integration, since it provides game downloads while also being a storefront for other stores (it's not always Steam).  Handling it yourself using a popup seems like the ideal option.

At the very least, if the Install button is enabled for a title, that means it should do something.

**Comment by UncleGoogle** [comment]
> Handling it yourself using a popup seems like the ideal option (option 1).

I'll do that.

> We likely shouldn't expect Galaxy to be able to handle keys, that seems out of scope of the application.

I wish we have support for keys at some point. humble is not special here, there are plenty key resellers, some of them are already in API list of PLATFORM_IDS, like `gg`, `playfire`.

> Additionally, not all keys are for Steam, so opening up in Steam may not be the right choice 100% of the time.
The key info from humble bundle API contain information about key type. I'm displaying this info, it is not hardcoded.

> Lastly, what do you think of not returning keys that have already been redeemed? This may be a good idea for a separate GitHub issue.

This is quite old feature ;) #6 
Open config to select proper checkbox.
